### ISSUE TITLE
Bounce back issue

### ISSUE THREAD

**Issue by blogbytes** [mhayes14/whmcs-pushover#1]
Hi

This plugin works as expected, however, when a user submits a ticket etc he receives a bounce back email when on used the pipe feature in whmcs to import the ticket. 

The ticket etc gets opened and the bounce back looks as following;

This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its recipients. This is a permanent error. The following address(es) failed:

  pipe to |/home/user/public_html/whmcs/crons/pipe.php
    generated by email@email.com

The following text was generated during the delivery attempt:

------ pipe to |/home/user/public_html/whmcs/crons/pipe.php
       generated by email@email.com ------

{"status":1,"request":"4966731a-1965-4b27-b2e2-6e904ece3c61"}

Any ideas?

**Comment by mikehayesuk** [comment]
Hi @blogbytes 

I believe this is caused by curl printing the Pushover API response by default. I've made a change in 835675ac5d356d3239d7ed6a10e84cb5d41a3ac3 which should fix this for you. Could you please apply the change and let me know?

Thanks
Mike

**Comment by blogbytes** [comment]
Thanks Mike, that did the trick.
Great plugin, works well :)
